# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: FLORIS
author: National Renewable Energy Laboratory
logo: gch.gif
copyright: '2022'
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/nrel/floris
  path_to_book: docs
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true

# Sphinx for API doc generation
sphinx:
  extra_extensions:
  - 'autoapi.extension'
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.viewcode'
  - 'sphinx_autodoc_typehints'
  - 'sphinxcontrib.autoyaml'
  config:
    language: 'python'
    autoapi_dirs:
    - '../floris'
    autoapi_add_toctree_entry: true
    autoyaml_level: 3

    # autoapi_add_objects_to_toctree: true  # WARNING: unknown config value 'autoapi_add_objects_to_toctree' in override, ignoring
    # autoapi_keep_files: true
    # autoapi_root: 'api_doc'  # default is autoapi/
    # autoapi_generate_api_docs: false  # default is true
    # - 'sphinx.ext.napoleon'   # Formats google and numpy docstring styles
